# -*- coding: utf-8 -*-
"""Fase2 Entendimiento de datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPOFrd-95MBw5eyqZqiiW3VUO1wGO7p3
"""

import pandas as pd

datos_consumo = pd.read_excel("Comidas.xlsx")

datos_consumo.head()

datos_consumo.shape

datos_consumo.columns

datos_consumo.dtypes

datos_consumo.info()

datos_consumo.describe()